import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    container2: {
        flex: 1,
        padding: 30,
    },
    container3: {
        display: "flex",
        width: '100%',
        padding: 30,
        top: '2%',
        flexDirection: 'column',
    },
    formContainer: {
        flex: 1,
        padding: 30,
        flexDirection: 'column',
        gap: 20,
    },
    mainScrollView: {
        flex: 1,
        width: '100%',
    },
    navbar: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        height: 50,
        backgroundColor: 'rgb(49,46,46)',
        shadowColor: '#656565',
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 4,
    },
    links: {
        display: 'flex',
        flexDirection: 'row',
        gap: 20,
    },
    link: {
        color: '#e5e0e0',
        fontSize: 16,
        fontFamily: 'PT Sans',
    },
    linkUnderline: {
        color: '#e5e0e0',
        fontSize: 16,
        fontFamily: 'PT Sans',
        textDecorationLine: 'underline',
    },
    icon: {
        marginRight: 5,
    },
    h1: {
        fontSize: 40,
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        textAlign: 'center',
        marginBottom: 30,
    },
    h2: {
        fontSize: 20,
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        textAlign: 'center',
        marginBottom: 20,
    },
    h3: {
        fontSize: 16,
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        textAlign: 'center',
        marginVertical: 30,
    },
    profileTitle: {
        fontSize: 20,
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        textAlign: 'center',
        marginVertical: 20,
    },
    form: {
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#e5e0e0',
        borderRadius: 10,
        padding: 30,
        width: '80%',
        top: '3%',
    },
    label: {
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        marginBottom: 5,
    },
    labelCode: {
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
        marginTop: 20,
        marginBottom: 5,
    },
    text: {
        paddingTop: 3,
        fontFamily: 'PT Sans',
        color: '#e5e0e0',
    },
    sentence: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    sentencePhone: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 15,
    },
    input: {
        backgroundColor: '#e5e0e0',
        borderRadius: 5,
        borderColor: '#3b3b3b',
        borderWidth: 1,
        padding: 10,
        marginBottom: 5,
    },
    button: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#313131',
        padding: 5,
        borderRadius: 5,
        width: 120,
    },
    userInfoContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
    },
    redirectLink: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#e5e0e0',
        color: '#3b3b3b',
        padding: 5,
        borderRadius: 5,
        width: 120,
    },
    image: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    post: {
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        height: 200,
        padding: 10,
        borderWidth: 1,
        borderColor: '#e5e0e0',
        borderRadius: 5,
    },
    error: {
        color: '#d52e2e',
        fontWeight: 'bold',
        fontFamily: 'PT Sans',
        letterSpacing: 1.1,
        fontSize: 12,
        marginBottom: 10,
    },
    thumbnailForm: {
        width: '100%',
        height: 200,
        objectFit: 'cover',
        borderRadius: 5,
    }
});